name: Build OverflowLimbo
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build JAR
        run: |
            chmod +x gradlew
            ./gradlew shadowJar --stacktrace
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OverflowLimbo-1.4
          path: build/libs
